[phases.setup]
nixPkgs = ["python", "postgresql"]

[phases.install]
cmds = [
    "python -m venv /app/.venv",
    "source /app/.venv/bin/activate",
    "pip install -r requirements.txt"
]

[start]
cmd = "gunicorn app:app"
